defaults: &defaults
  working_directory: ~/hahow
  docker:
    - image: circleci/node:dubnium
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/hahow
      # run tests!
      - run: yarn test
      # run visual tests
      - run: yarn chromatic --exit-zero-on-changes
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/hahow
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      # Deploy Storybook to GitHub Pages
      - run: yarn deploy-storybook
workflows:
  version: 2
  build:
    jobs:
      - setup
      - test:
          requires:
            - setup
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
