defaults: &container
  working_directory: ~/hahow
  docker:
    - image: circleci/node:dubnium
version: 2
jobs:
  setup:
    <<: *container
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  build_npm:
    <<: *container
    steps:
      - attach_workspace:
          at: ~/hahow
      - run: yarn build
  build_storybook:
    <<: *container
    steps:
      - attach_workspace:
          at: ~/hahow
      - run: yarn build-storybook
  test:
    <<: *container
    steps:
      - attach_workspace:
          at: ~/hahow
      - run: yarn test
      # Run visual tests
      - run: yarn chromatic --exit-zero-on-changes
  # Deploy Storybook to GitHub Pages
  deploy_storybook:
    <<: *container
    steps:
      - attach_workspace:
          at: ~/hahow
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run: yarn deploy-storybook --ci
  publish_npm:
    <<: *container
    steps:
      - attach_workspace:
          at: ~/hahow
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/hahow/.npmrc
      - run: npm version
      - run: npm publish
workflows:
  version: 2
  build:
    jobs:
      - setup
      - build_npm:
          requires:
            - setup
          filters:
            branches:
              ignore:
                - master
      - build_storybook:
          requires:
            - setup
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - setup
      - deploy_storybook:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      # TODO: publish_npm: